# Generated by Django 3.1.5 on 2021-11-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Careers',
            new_name='Career',
        ),
    ]
