# Generated by Django 3.1.5 on 2021-11-30 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mockerapp', '0002_auto_20211130_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/ads')),
                ('videoad', models.FileField(blank=True, null=True, upload_to='uploads/advideos')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/teamimages')),
                ('name', models.CharField(max_length=200)),
                ('jobtitle', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=5000)),
                ('linkedinprofile', models.CharField(blank=True, max_length=400, null=True)),
                ('Instagramprofile', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='tutorimage1',
            field=models.ImageField(default='', upload_to='uploads/tutorimages'),
        ),
        migrations.AddField(
            model_name='membership',
            name='tutorimage2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorimages'),
        ),
        migrations.AddField(
            model_name='membership',
            name='tutorimage3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/tutorimages'),
        ),
        migrations.AddField(
            model_name='membership',
            name='tutors',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('phone', models.PositiveIntegerField(default=0)),
                ('address', models.TextField(max_length=3000)),
                ('gender', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
