# Generated by Django 3.1.5 on 2021-11-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockerapp', '0003_auto_20211130_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Ad',
        ),
    ]
